---
version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "cluster.name=docker-cluster"
      - "discovery.type=single-node"
    volumes:
      - esdata:/usr/share/elasticsearch/data
volumes:
  esdata: