---
version: '3.7'
services:
  zipkin-elasticsearch:
    image: openzipkin/zipkin-elasticsearch6:2.11
    hostname: zipkin-elasticsearch
    container_name: zipkin-elasticsearch
    ports:
      - 19200:9200
  zipkin:
    image: openzipkin/zipkin:2.11
    container_name: zipkin
    environment:
      STORAGE_TYPE: elasticsearch
      ES_HOSTS: zipkin-elasticsearch
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      # Uncomment to enable self-tracing
      # SELF_TRACING_ENABLED: "true"
      # Uncomment to enable debug logging
      # JAVA_OPTS: "-Dlogging.level.zipkin=DEBUG -Dlogging.level.zipkin2=DEBUG"
    ports:
      - 9411:9411
    depends_on:
      - zipkin-elasticsearch
  zipkin-dependencies:
    image: openzipkin/zipkin-dependencies:2
    hostname: zipkin-dependencies
    container_name: zipkin-dependencies
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=elasticsearch
    depends_on:
      - zipkin-elasticsearch
volumes:
  data:
networks:
  default:
    external:
      name: composes
