---
version: '3.7'
services:
  zipkin-mysql:
    image: openzipkin/zipkin-mysql:2.11
    hostname: zipkin-mysql
    container_name: zipkin-mysql
    volumes:
      - data:/mysql/data
  zipkin:
    image: openzipkin/zipkin:2.11
    container_name: zipkin
    environment:
      STORAGE_TYPE: mysql
      MYSQL_HOST: zipkin-mysql
      KAFKA_BOOTSTRAP_SERVERS: broker:9092
      # Uncomment to enable self-tracing
      # SELF_TRACING_ENABLED: "true"
      # Uncomment to enable debug logging
      # JAVA_OPTS: "-Dlogging.level.zipkin=DEBUG -Dlogging.level.zipkin2=DEBUG"
    ports:
      - 9411:9411
    depends_on:
      - zipkin-mysql
  zipkin-dependencies:
    image: openzipkin/zipkin-dependencies:2
    hostname: zipkin-dependencies
    container_name: zipkin-dependencies
    environment:
      STORAGE_TYPE: mysql
      MYSQL_HOST: zipkin-mysql
      MYSQL_USER: zipkin
      MYSQL_PASS: zipkin
    depends_on:
      - zipkin-mysql
volumes:
  data:
networks:
  default:
    external:
      name: composes
