version: '3.8'
services:
  kafka:
    build:
      context: ../base
      args:
        - AK_REPO=https://github.com/aiven/kafka
        - AK_BRANCH=3.3-2022-10-06-tiered-storage
        - KAFKA_VERSION=3.3.2-SNAPSHOT
    command:
      - /bin/sh
      - -c
      - |
        cat config/kraft/server.properties
        kafka-storage.sh format -t $KAFKA_CLUSTER_ID -c config/kraft/server.properties --ignore-formatted
        kafka-server-start.sh config/kraft/server.properties

    #   - kafka-server-start.sh
    #   - config/server.properties
    #   - --override
    #   - zookeeper.connect=zookeeper:2181
    #   - --override
    #   - listeners=BROKER://kafka:29092,EXTERNAL://kafka:9092
    #   - --override
    #   - advertised.listeners=BROKER://kafka:29092,EXTERNAL://localhost:9092
    #   - --override
    #   - listener.security.protocol.map=BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT
    #   - --override
    #   - inter.broker.listener.name=BROKER
    # ports:
    #   - 9092:9092