---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_OPTS: '-Dcom.sun.management.jmxremote.port=5555'
    volumes:
      - zk_data:/var/lib/zookeeper/data
      - zk_tx_logs:/var/lib/zookeeper/log
  zookeeper-jmx-exporter:
    image: jeqo/prometheus-jmx-exporter-httpserver:0.3.1
    container_name: zookeeper-jmx-exporter
    volumes:
      - ./zookeeper-jmx-exporter/httpserver.yml:/jmx-exporter/config/httpserver.yml
    ports:
      - 7556:7556
    environment:
      JMX_EXPORTER_HTTP_PORT: 7556
  kafka:
    image: confluentinc/cp-kafka:5.0.0
    hostname: kafka
    container_name: kafka
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OPTS: '-Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=5555'
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/var/lib/kafka/data
  kafka-jmx-exporter:
    image: jeqo/prometheus-jmx-exporter-httpserver:0.3.1
    container_name: kafka-jmx-exporter
    volumes:
      - ./kafka-jmx-exporter/httpserver.yml:/jmx-exporter/config/httpserver.yml
    ports:
      - 7557:7557
    environment:
      JMX_EXPORTER_HTTP_PORT: 7557
volumes:
  zk_data:
  zk_tx_logs:
  kafka_data:
networks:
  default:
    external:
      name: composes
