---
version: '3.4'
x-kafka-env:
  &kafka-env
  KAFKA_ZOOKEEPER_CONNECT: zk1:2181
  KAFKA_NUM_PARTITIONS: 12
  KAFKA_DEFAULT_REPLICATION_FACTOR: 3
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
  KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
  KAFKA_MIN_INSYNC_REPLICAS: 2

services:
  zk1:
    image: confluentinc/cp-zookeeper:${CP_VERSION}
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka1:
    image: confluentinc/cp-kafka:${CP_VERSION}
    ports:
      - 19092:19092
    environment: 
      << : *kafka-env
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:19092
    volumes:
      - kafka1-data:/var/lib/kafka/data:rw

  kafka2:
    image: confluentinc/cp-kafka:${CP_VERSION}
    ports:
      - 29092:29092
    environment: 
      << : *kafka-env
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092,PLAINTEXT_HOST://localhost:29092
    volumes:
      - kafka2-data:/var/lib/kafka/data:rw

  kafka3:
    image: confluentinc/cp-kafka:${CP_VERSION}
    ports:
      - 39092:39092
    environment: 
      << : *kafka-env
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092,PLAINTEXT_HOST://localhost:39092
    volumes:
      - kafka3-data:/var/lib/kafka/data:rw

  kafka-client:
    image: confluentinc/cp-kafka:${CP_VERSION}
    entrypoint: /bin/sh
    tty: true

volumes:
  kafka1-data:
  kafka2-data:
  kafka3-data: