---
version: '3.4'
x-zk-env:
  &zk-env
  ZOOKEEPER_TICK_TIME: 2000
  ZOOKEEPER_INIT_LIMIT: 5
  ZOOKEEPER_SYNC_LIMIT: 2
  ZOOKEEPER_SERVERS: zk1:2888:3888;zk2:2888:3888;zk3:2888:3888
  EXTRA_ARGS: -javaagent:/opt/prometheus-jmx-exporter/jmx_prometheus_javaagent.jar=1234:/opt/prometheus-jmx-exporter/zookeeper.yml
services:
  zk1:
    image: confluentinc/cp-zookeeper:${CP_VERSION}
    ports:
      - 12181:12181
    environment:
      << : *zk-env
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 12181
    volumes:
      - ./../prometheus-jmx-exporter:/opt/prometheus-jmx-exporter
  zk2: 
    image: confluentinc/cp-zookeeper:${CP_VERSION}
    ports:
      - 22181:22181
    environment:
      << : *zk-env
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 22181
    volumes:
      - ./../prometheus-jmx-exporter:/opt/prometheus-jmx-exporter
  zk3:
    image: confluentinc/cp-zookeeper:${CP_VERSION}
    ports:
      - 32181:32181
    environment:
      << : *zk-env
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 32181
    volumes:
      - ./../prometheus-jmx-exporter:/opt/prometheus-jmx-exporter