---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.1
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_OPTS: '-Dcom.sun.management.jmxremote.port=5555'
    volumes:
      - zk_data:/var/lib/zookeeper/data
      - zk_tx_logs:/var/lib/zookeeper/log
  kafka0:
    image: confluentinc/cp-kafka:5.2.1
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka0:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OPTS: '-Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=5555'
    depends_on:
      - zookeeper
    volumes:
      - kafka0_data:/var/lib/kafka/data
  kafka1:
    image: confluentinc/cp-kafka:5.2.1
    ports:
      - 9093:9093
      - 29093:29093
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9093,PLAINTEXT_HOST://localhost:29093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OPTS: '-Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=5555'
    depends_on:
      - zookeeper
    volumes:
      - kafka1_data:/var/lib/kafka/data
  kafka2:
    image: confluentinc/cp-kafka:5.2.1
    ports:
      - 9094:9094
      - 29094:29094
    environment:
      KAFKA_BROKER_ID: 102
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9094,PLAINTEXT_HOST://localhost:29094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OPTS: '-Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=5555'
    depends_on:
      - zookeeper
    volumes:
      - kafka2_data:/var/lib/kafka/data

  # JMX Exporters #
  zookeeper-jmx-exporter:
    image: jeqo/prometheus-jmx-exporter-httpserver:0.3.1
    volumes:
      - ./zookeeper-jmx-exporter/httpserver.yml:/jmx-exporter/config/httpserver.yml
    ports:
      - 7556:7556
    environment:
      JMX_EXPORTER_HTTP_PORT: 7556
  kafka-jmx-exporter0:
    image: jeqo/prometheus-jmx-exporter-httpserver:0.3.1
    volumes:
      - ./kafka-jmx-exporter0/httpserver.yml:/jmx-exporter/config/httpserver.yml
    ports:
      - 7557:7557
    environment:
      JMX_EXPORTER_HTTP_PORT: 7557
  kafka-jmx-exporter1:
    image: jeqo/prometheus-jmx-exporter-httpserver:0.3.1
    volumes:
      - ./kafka-jmx-exporter1/httpserver.yml:/jmx-exporter/config/httpserver.yml
    ports:
      - 7558:7558
    environment:
      JMX_EXPORTER_HTTP_PORT: 7558
  kafka-jmx-exporter2:
    image: jeqo/prometheus-jmx-exporter-httpserver:0.3.1
    volumes:
      - ./kafka-jmx-exporter2/httpserver.yml:/jmx-exporter/config/httpserver.yml
    ports:
      - 7559:7559
    environment:
      JMX_EXPORTER_HTTP_PORT: 7559
volumes:
  zk_data:
  zk_tx_logs:
  kafka0_data:
  kafka1_data:
  kafka2_data:
networks:
  default:
    external:
      name: composes
