---
version: '3.7'
services:
  zipkin-cassandra0:
    image: openzipkin/zipkin-cassandra:2.11
    # hostname: cassandra0
    ports:
      - 9042:9042
  zipkin-cassandra1:
    image: openzipkin/zipkin-cassandra:2.11
    # image: cassandra:3.11
    # hostname: cassandra1
    environment:
      CASSANDRA_SEEDS: zipkin-cassandra0
    ports:
      - 9043:9042
  zipkin-cassandra2:
    image: openzipkin/zipkin-cassandra:2.11
    # image: cassandra:3.11
    # hostname: cassandra2
    environment:
      CASSANDRA_SEEDS: zipkin-cassandra0
    ports:
      - 9044:9042
  # zipkin-cassandra:
  #  image: openzipkin/zipkin-cassandra:2.11
  #  ports:
  #    - 9042:9042
  zipkin:
    image: openzipkin/zipkin:2.11
    environment:
      STORAGE_TYPE: cassandra3
      CASSANDRA_CONTACT_POINTS: zipkin-cassandra0,zipkin-cassandra1,zipkin-cassandra2
      KAFKA_BOOTSTRAP_SERVERS: kafka0:9092,kafka1:9093,kafka2:9094
    ports:
      - 9412:9411
    depends_on:
      - zipkin-cassandra0
volumes:
  data:
networks:
  default:
    external:
      name: composes
