---
version: '3.4'
services:
  grafana:
    image: grafana/grafana
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel
    ports:
      - 3000:3000
    volumes:
      - ./../grafana/:/etc/grafana/provisioning/
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./../prometheus/config/:/etc/prometheus/
  ccloud_exporter:
    image: dabz/ccloudexporter
    environment:
      CCLOUD_USER: ${CCLOUD_USER}
      CCLOUD_PASSWORD: ${CCLOUD_PASSWORD}
    command: -cluster ${CCLOUD_CLUSTER}