---
version: 3
services:
  zk1:
    image: confluentinc/cp-zookeeper:${CP_VERSION}
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      EXTRA_ARGS: -javaagent:/opt/prometheus-jmx-exporter/jmx_prometheus_javaagent.jar=1234:/opt/prometheus-jmx-exporter/zookeeper.yml
    volumes:
      - ./../prometheus-jmx-exporter:/opt/prometheus-jmx-exporter