---
version: '3.4'

x-kafka-env:
  &kafka-env
  KAFKA_ZOOKEEPER_CONNECT: zk1:2181
  
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:SASL_PLAINTEXT,TOKEN:SASL_PLAINTEXT,INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
  
  KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
  KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN

  KAFKA_LISTENER_NAME_BROKER_SASL_ENABLED_MECHANISMS: PLAIN
  KAFKA_LISTENER_NAME_BROKER_PLAIN_SASL_JAAS_CONFIG: |
                                                      \
                                                      org.apache.kafka.common.security.plain.PlainLoginModule required \
                                                      username="admin" \
                                                      password="admin-secret" \
                                                      user_admin="admin-secret" \
                                                      user_mds="mds-secret";
  
  KAFKA_LISTENER_NAME_INTERNAL_SASL_ENABLED_MECHANISMS: PLAIN
  KAFKA_LISTENER_NAME_INTERNAL_PLAIN_SASL_JAAS_CONFIG: |
                                                      \
                                                      org.apache.kafka.common.security.plain.PlainLoginModule required \
                                                      user_intclient1="client1-secret" \
                                                      user_intclient2="client2-secret";
  
  KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS: PLAIN
  KAFKA_LISTENER_NAME_EXTERNAL_PLAIN_SASL_JAAS_CONFIG: |
                                                      \
                                                      org.apache.kafka.common.security.plain.PlainLoginModule required \
                                                      user_extclient1="client1-secret" \
                                                      user_extclient2="client2-secret";
  
  KAFKA_LISTENER_NAME_TOKEN_SASL_ENABLED_MECHANISMS: OAUTHBEARER
  KAFKA_LISTENER_NAME_TOKEN_OAUTHBEARER_SASL_SERVER_CALLBACK_HANDLER_CLASS: io.confluent.kafka.server.plugins.auth.token.TokenBearerValidatorCallbackHandler
  KAFKA_LISTENER_NAME_TOKEN_OAUTHBEARER_SASL_LOGIN_CALLBACK_HANDLER_CLASS: io.confluent.kafka.server.plugins.auth.token.TokenBearerServerLoginCallbackHandler
  KAFKA_LISTENER_NAME_TOKEN_OAUTHBEARER_SASL_JAAS_CONFIG: |
                                                       \
                                                       org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
                                                       publicKeyPath="/tmp/conf/public.pem";
  
  KAFKA_AUTHORIZER_CLASS_NAME: io.confluent.kafka.security.authorizer.ConfluentServerAuthorizer
  KAFKA_SUPER_USERS: User:admin;User:mds;User:superUser
  
  # KAFKA_CONFLUENT_AUTHORIZER_SCOPE: myCluster
  # KAFKA_CONFLUENT_AUTHORIZER_METADATA_PROVIDER: RBAC
  KAFKA_CONFLUENT_AUTHORIZER_ACCESS_RULE_PROVIDERS: CONFLUENT,ZK_ACL
  KAFKA_CONFLUENT_AUTHORIZER_GROUP_PROVIDER: RBAC

  KAFKA_CONFLUENT_METADATA_SECURITY_PROTOCOL: SASL_PLAINTEXT
  KAFKA_CONFLUENT_METADATA_BOOTSTRAP_SERVERS: BROKER://localhost:9092
  KAFKA_CONFLUENT_METADATA_SASL_MECHANISM: PLAIN
  KAFKA_CONFLUENT_METADATA_SASL_JAAS_CONFIG: |
                                              \
                                              org.apache.kafka.common.security.plain.PlainLoginModule required \
                                              username="mds" \
                                              password="mds-secret";
  
  KAFKA_CONFLUENT_METADATA_SERVER_LISTENERS: http://0.0.0.0:8090
  KAFKA_CONFLUENT_METADATA_SERVER_AUTHENTICATION_METHOD: BEARER
  KAFKA_CONFLUENT_METADATA_SERVER_AUTHENTICATION_ROLES: '**'
  KAFKA_CONFLUENT_METADATA_SERVER_TOKEN_AUTH_ENABLE: 'true'
  KAFKA_CONFLUENT_METADATA_SERVER_TOKEN_MAX_LIFETIME_MS: 3600000
  KAFKA_CONFLUENT_METADATA_SERVER_TOKEN_SIGNATURE_ALGORITHM: RS256
  KAFKA_CONFLUENT_METADATA_SERVER_TOKEN_KEY_PATH: /tmp/conf/keypair.pem
  KAFKA_CONFLUENT_METADATA_SERVER_PUBLIC_KEY_PATH: /tmp/conf/public.pem
  # KAFKA_CONFLUENT_METADATA_SERVER_SCOPE: ''
  
  KAFKA_LDAP_JAVA_NAMING_FACTORY_INITIAL: com.sun.jndi.ldap.LdapCtxFactory
  KAFKA_LDAP_COM_SUN_JNDI_LDAP_READ_TIMEOUT: 3000
  KAFKA_LDAP_JAVA_NAMING_PROVIDER_URL: ldap://ldap:389
  KAFKA_LDAP_JAVA_NAMING_SECURITY_PRINCIPAL: cn=admin,dc=confluent,dc=io
  KAFKA_LDAP_JAVA_NAMING_SECURITY_CREDENTIALS: admin
  KAFKA_LDAP_JAVA_NAMING_SECURITY_AUTHENTICATION: simple
  KAFKA_LDAP_USER_SEARCH_BASE: ou=users,dc=confluent,dc=io
  KAFKA_LDAP_GROUP_SEARCH_BASE: ou=groups,dc=confluent,dc=io
  KAFKA_LDAP_USER_NAME_ATTRIBUTE: uid
  KAFKA_LDAP_USER_OBJECT_CLASS: inetOrgPerson
  KAFKA_LDAP_USER_MEMBEROF_ATTRIBUTE: ou
  KAFKA_LDAP_GROUP_NAME_ATTRIBUTE: cn
  KAFKA_LDAP_GROUP_OBJECT_CLASS: posixGroup

  KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
  CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9092,kafka3:9092
  CONFLUENT_METRICS_REPORTER_SECURITY_PROTOCOL: SASL_PLAINTEXT
  CONFLUENT_METRICS_REPORTER_SASL_MECHANISM: PLAIN
  CONFLUENT_METRICS_REPORTER_SASL_JAAS_CONFIG: |
                                                \
                                                org.apache.kafka.common.security.plain.PlainLoginModule required \
                                                username="admin" \
                                                password="admin-secret";
  
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2

  KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 3
  KAFKA_CONFLUENT_LICENSE_TOPIC_MIN_ISR: 2
  KAFKA_CONFLUENT_METADATA_TOPIC_REPLICATION_FACTOR: 3
  CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 3

  KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
  CONFLUENT_SUPPORT_CUSTOMER_ID: anonymous

  KAFKA_OPTS: "
    -javaagent:/opt/prometheus-jmx-exporter/jmx_prometheus_javaagent.jar=1234:/opt/prometheus-jmx-exporter/kafka-broker.yaml
  "

services:
  # cp-core
  zk1:
    image: confluentinc/cp-zookeeper:${CP_VERSION}
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      EXTRA_ARGS: -javaagent:/opt/prometheus-jmx-exporter/jmx_prometheus_javaagent.jar=1234:/opt/prometheus-jmx-exporter/zookeeper.yml
    volumes:
      - ./../volumes/prometheus-jmx-exporter:/opt/prometheus-jmx-exporter
  kafka1:
    image: confluentinc/cp-server:${CP_VERSION}
    ports:
      - 8091:8090
      - 9091:9092
      - 10091:10092
      - 11091:11092
      - 12091:12091
    environment:
      << : *kafka-env
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka1:9092,TOKEN://kafka1:10092,INTERNAL://kafka1:11092,EXTERNAL://localhost:12091
      KAFKA_CONFLUENT_METADATA_SERVER_ADVERTISED_LISTENERS: http://kafka1:8090
    volumes:
      - ./conf:/tmp/conf
      - ./../volumes/prometheus-jmx-exporter:/opt/prometheus-jmx-exporter
    depends_on:
      - zk1

  kafka2:
    image: confluentinc/cp-server:${CP_VERSION}
    ports:
      - 8092:8090
      - 9092:9092
      - 10092:10092
      - 11092:11092
      - 12092:12092
    environment:
      << : *kafka-env
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka2:9092,TOKEN://kafka2:10092,INTERNAL://kafka2:11092,EXTERNAL://localhost:12092
      KAFKA_CONFLUENT_METADATA_SERVER_ADVERTISED_LISTENERS: http://kafka2:8090
    volumes:
      - ./conf:/tmp/conf
      - ./../volumes/prometheus-jmx-exporter:/opt/prometheus-jmx-exporter
    depends_on:
      - zk1
  kafka3:
    image: confluentinc/cp-server:${CP_VERSION}
    ports:
      - 8093:8090
      - 9093:9092
      - 10093:10092
      - 11093:11092
      - 12093:12093
    environment:
      << : *kafka-env
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka3:9092,TOKEN://kafka3:10092,INTERNAL://kafka3:11092,EXTERNAL://localhost:12093
      KAFKA_CONFLUENT_METADATA_SERVER_ADVERTISED_LISTENERS: http://kafka3:8090
    volumes:
      - ./conf:/tmp/conf
      - ./../volumes/prometheus-jmx-exporter:/opt/prometheus-jmx-exporter
    depends_on:
      - zk1
