---
version: '3'
services:
  grafana:
    image: grafana/grafana:5.2.2
    hostname: grafana
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
networks:
  default:
    external:
      name: composes
