---
version: '3'
services:
  grafana:
    image: grafana/grafana:5.3.4
    ports:
      - 3000:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    volumes:
      - grafana_data:/var/lib/kafka
volumes:
  grafana_data:
networks:
  default:
    external:
      name: composes
