---
version: '3.7'
services:
  consul:
    image: consul:1.2.2
    hostname: consul
    container_name: consul
    restart: always
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:8600
      - 8600:8600/udp
    command: "agent -server -bootstrap-expect 1 -ui -bind 127.0.0.1 -client 0.0.0.0"
    volumes:
      - data:/consul/data

volumes:
  data:

networks:
  default:
    external:
      name: composes
