version: '3.4'
services:
  prometheus:
    image: prom/prometheus:v2.18.1
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/config/:/etc/prometheus/
  grafana:
    image: grafana/grafana:7.0.6
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password
      GF_USERS_ALLOW_SIGN_UP: "false"
    ports:
      - 3000:3000
    volumes:
      - ./grafana/:/etc/grafana/provisioning/