---
version: '3'
services:
  kafka-manager:
    image: syscomiddleware/kafka-manager:1.3.3
    environment:
      ZK_HOSTS: zookeeper:2181
    ports:
      - 9000:9000
networks:
  default:
    external:
      name: composes
