---
version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts-alpine
    hostname: jenkins
    container_name: jenkins
    restart: always
    ports:
      - 7808:8080
    volumes:
      - data:/var/jenkins_home
volumes:
  data:

networks:
  default:
    external:
      name: composes
