---
version: '3.4'
x-kafka-env:
  &kafka-env
  KAFKA_BROKER_ID: 1
  KAFKA_ZOOKEEPER_CONNECT: zk1:2181
  KAFKA_NUM_PARTITIONS: 12
  KAFKA_DEFAULT_REPLICATION_FACTOR: 3
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SSL:SSL,SSL_HOST:SSL
  KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:19092,SSL://kafka1:9093,SSL_HOST://localhost:19093
  
  KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL

  KAFKA_SSL_KEYSTORE_TYPE: PKCS12
  KAFKA_SSL_KEYSTORE_FILENAME: kafka1.keystore.p12
  KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka1_keystore_credential
  KAFKA_SSL_KEY_CREDENTIALS: kafka1_key_credential
  KAFKA_SSL_TRUSTSTORE_TYPE: PKCS12
  KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/truststore.p12
  KAFKA_SSL_TRUSTSTORE_PASSWORD: test1234
  KAFKA_SSL_CLIENT_AUTH: none
  KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: " "

  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
  KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1

  KAFKA_OPTS: "
    -Djavax.net.debug=handshake
    -Djava.security.auth.login.config=/etc/kafka/kafka_jaas.conf 
    -javaagent:/opt/prometheus-jmx-exporter/jmx_prometheus_javaagent.jar=1234:/opt/prometheus-jmx-exporter/kafka-broker.yaml
  "

services:
  kafka1:
    image: confluentinc/cp-kafka:${CP_VERSION}
    ports:
      - 19092:19092
      - 19093:19093
    environment: *kafka-env
    volumes:
      - ./../prometheus-jmx-exporter:/opt/prometheus-jmx-exporter
      - ./no-auth/kafka_jaas.conf:/etc/kafka/kafka_jaas.conf
      - ./one-way-tls/super.properties:/etc/kafka/super.properties
      - ./one-way-tls/admin.properties:/etc/kafka/admin.properties
      - ./one-way-tls/producer.properties:/etc/kafka/producer.properties
      - ./one-way-tls/consumer.properties:/etc/kafka/consumer.properties
      - ./tls:/etc/kafka/secrets
  kafka2:
    image: confluentinc/cp-kafka:${CP_VERSION}
    ports:
      - 29092:29092
      - 29093:29093
    environment: 
      << : *kafka-env
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092,PLAINTEXT_HOST://localhost:29092,SSL://kafka2:9093,SSL_HOST://localhost:29093

      KAFKA_SSL_KEYSTORE_FILENAME: kafka2.keystore.p12
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka2_keystore_credential
      KAFKA_SSL_KEY_CREDENTIALS: kafka2_key_credential
    volumes:
      - ./../prometheus-jmx-exporter:/opt/prometheus-jmx-exporter
      - ./no-auth/kafka_jaas.conf:/etc/kafka/kafka_jaas.conf
      - ./tls:/etc/kafka/secrets

  kafka3:
    image: confluentinc/cp-kafka:${CP_VERSION}
    ports:
      - 39092:39092
      - 39093:39093
    environment: 
      << : *kafka-env
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092,PLAINTEXT_HOST://localhost:39092,SSL://kafka3:9093,SSL_HOST://localhost:39093
      
      KAFKA_SSL_KEYSTORE_FILENAME: kafka3.keystore.p12
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka3_keystore_credential
      KAFKA_SSL_KEY_CREDENTIALS: kafka3_key_credential
    volumes:
      - ./../prometheus-jmx-exporter:/opt/prometheus-jmx-exporter
      - ./no-auth/kafka_jaas.conf:/etc/kafka/kafka_jaas.conf
      - ./tls:/etc/kafka/secrets