
---
version: '3.4'
services:
  zk1:
    image: confluentinc/cp-zookeeper:${CP_VERSION}
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_AUTH_PROVIDER_SASL: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
      ZOOKEEPER_REQUIRE_CLIENT_AUTH_SCHEME: sasl
      EXTRA_ARGS: "
        -Djava.security.auth.login.config=/etc/kafka/zookeeper_jaas.conf 
        -javaagent:/opt/prometheus-jmx-exporter/jmx_prometheus_javaagent.jar=1234:/opt/prometheus-jmx-exporter/zookeeper.yml
      "
    volumes:
      - ./../prometheus-jmx-exporter:/opt/prometheus-jmx-exporter
      - ./zk/zookeeper_jaas.conf:/etc/kafka/zookeeper_jaas.conf
  kafka1:
    image: confluentinc/cp-kafka:${CP_VERSION}
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_PLAINTEXT_HOST:SASL_PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:19092,PLAINTEXT_HOST://localhost:9092,SASL_PLAINTEXT://kafka1:19093,SASL_PLAINTEXT_HOST://localhost:9093
      
      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      
      KAFKA_OPTS: "
        -Djava.security.auth.login.config=/etc/kafka/kafka_jaas.conf 
        -javaagent:/opt/prometheus-jmx-exporter/jmx_prometheus_javaagent.jar=1234:/opt/prometheus-jmx-exporter/kafka-broker.yaml
      "
    volumes:
      - ./../prometheus-jmx-exporter:/opt/prometheus-jmx-exporter
      - ./single-sasl-plain/kafka_jaas.conf:/etc/kafka/kafka_jaas.conf
