---
version: '3.4'
services:
  zk1:
    image: confluentinc/cp-zookeeper:${CP_VERSION}
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_AUTH_PROVIDER_SASL: org.apache.zookeeper.server.auth.SASLAuthenticationProvider
      ZOOKEEPER_REQUIRE_CLIENT_AUTH_SCHEME: sasl
      EXTRA_ARGS: "
        -Djava.security.auth.login.config=/etc/kafka/zookeeper_jaas.conf 
        -javaagent:/opt/prometheus-jmx-exporter/jmx_prometheus_javaagent.jar=1234:/opt/prometheus-jmx-exporter/zookeeper.yml
      "
    volumes:
      - ./../prometheus-jmx-exporter:/opt/prometheus-jmx-exporter
      - ./zk/zookeeper_jaas.conf:/etc/kafka/zookeeper_jaas.conf
  kafka-client:
    image: confluentinc/cp-kafka:${CP_VERSION}
    entrypoint: /bin/sh
    tty: true