---
version: '3.7'
services:
  zipkin-elasticsearch:
    image: openzipkin/zipkin-elasticsearch6:2.11
    ports:
      - 19200:9200
  zipkin:
    image: openzipkin/zipkin:2.11
    environment:
      STORAGE_TYPE: elasticsearch
      ES_HOSTS: zipkin-elasticsearch
      KAFKA_BOOTSTRAP_SERVERS: kafka0:9092,kafka1:9093,kafka2:9094
    ports:
      - 9411:9411
    depends_on:
      - zipkin-elasticsearch
volumes:
  data:
networks:
  default:
    external:
      name: composes
