---
version: '3'
services:
  kafka:
    environment:
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
  schema-registry:
    image: confluentinc/cp-schema-registry:${CP_VERSION}
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:19092
    depends_on:
      - kafka
