---
version: '3'
services:
  kafka-rest:
    image: confluentinc/cp-kafka-rest:${CP_VERSION}
    ports:
      - 8082:8082
    environment:
      KAFKA_REST_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:19092
      KAFKA_REST_HOST_NAME: "0.0.0.0"
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-registry:8081
    depends_on: 
      - kafka
      - schema-registry