---
version: '3'
services: 
  schema-registry:
    image: confluentinc/cp-schema-registry:${CP_VERSION}
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:19092
    depends_on:
      - kafka