---
version: '3'
services:
  schema-registry:
    image: confluentinc/cp-schema-registry:5.0.0
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: localhost
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka0:9092,kafka1:9093,kafka2:9094
      SCHEMA_REGISTRY_OPTS: '-Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=5555'
  schema-registry-jmx_exporter:
    image: jeqo/prometheus-jmx-exporter-httpserver:0.3.1
    volumes:
      - ./schema-registry-jmx-exporter/httpserver.yml:/jmx-exporter/config/httpserver.yml
    ports:
      - 7566:7566
    environment:
      JMX_EXPORTER_HTTP_PORT: 7566

networks:
  default:
    external:
      name: composes

