---
version: '3'
services:
  schema-registry:
    image: confluentinc/cp-schema-registry:5.0.0
    hostname: schema-registry
    container_name: schema-registry
    ports:
      - 7081:7081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: localhost
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:7081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://broker:9092
      SCHEMA_REGISTRY_OPTS: '-Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=5555'
  schema-registry-jmx_exporter:
    image: jeqo/prometheus-jmx-exporter-httpserver:0.3.1
    container_name: schema-registry-jmx-exporter
    volumes:
      - ./schema-registry-jmx-exporter/httpserver.yml:/jmx-exporter/config/httpserver.yml
    ports:
      - 7558:7558
    environment:
      JMX_EXPORTER_HTTP_PORT: 7558

networks:
  default:
    external:
      name: composes

